stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build store:
  stage: build
  image: node:10.16.0-alpine
  before_script:
    - cd store
    - cp example.env ./.env
    - cp example.env ./dev.env
    - npm i
  artifacts:
    paths:
      - node_modules/

build modules-server:
  stage: build
  image: node:10.16.0-alpine
  before_script:
    - cd modules-server
    - cp example.env ./.env
    - cp example.env ./dev.env
    - npm i
  artifacts:
    paths:
      - node_modules/

build typescript-express-module-example:
  stage: build
  image: node:10.16.0-alpine
  before_script:
    - cd modules/typescript-express-module-example
    - cp example.env ./.env
    - cp example.env ./dev.env
    - npm i
  artifacts:
    paths:
      - node_modules/

test store:
  stage: test
  image: node:10.16.0-alpine
  services:
    - name: elasticsearch:7.5.1
      alias: elasticsearch
      command: ["bin/elasticsearch", "-Ediscovery.type=single-node"]
  variables:
    DB_SERVER: "http://elasticsearch:9200"
  before_script:
    - cd store
  script:
    - npm run ci

test modules-server:
  stage: test
  image: node:10.16.0-alpine
  services:
    - name: postgres
      alias: postgres
  variables:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: modules
  before_script:
    - cd modules-server
  script:
    - npm run ci
