image: docker:latest

stages:
  - test

store-test:
  stage: test
  services:
    - docker:dind
  before_script:
    - apk --update add nodejs
    - cd store
    - cp example.env ./.env
    - cp example.env ./dev.env
    - npm i
  script:
    - npm test
