stages:
  - test

store-test:
  stage: test
  image: ubuntu
  before_script:
    - curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
    - apt install nodejs
    - cd store
    - cp example.env ./.env
    - cp example.env ./dev.env
    - npm i
  script:
    - npm test
