image: docker:19.03.0

stages:
  - test

store-test:
  stage: test
  services:
    - docker:19.03.0-dind
  before_script:
    - apk --update add docker-compose
    - apk --update add nodejs
    - apk --update add npm
    - cd store
    - cp example.env ./.env
    - cp example.env ./dev.env
    - npm i
  script:
    - npm run ci

modules-server-test:
  stage: test
  services:
    - docker:19.03.0-dind
  before_script:
    - apk --update add docker-compose
    - apk --update add nodejs
    - apk --update add npm
    - cd modules-server
    - cp example.env ./.env
    - cp example.env ./dev.env
    - npm i
    - cat /etc/hosts
  script:
    - npm run ci
