image: docker

stages:
  - test

store-test:
  stage: test
  services:
    - name: docker:dind
  before_script:
    - apk --update add docker-compose
    - apk --update add nodejs
    - apk --update add npm
    - apk add --update curl && rm -rf /var/cache/apk/*
    - cd store
    - cp example.env ./.env
    - cp example.env ./dev.env
    - npm i
    - docker-compose -f docker-compose.test.yml up -d
    - sleep 15
    - docker ps -a
    - curl http://docker:9200
  script:
    - npm run ci
