image: docker:19.03.0

stages:
  - test

store-test:
  stage: test
  services:
    - docker:19.03.0-dind
  before_script:
    - apk --update add docker-compose
    - apk --update add nodejs
    - apk --update add npm
    - cd store
    - cp example.env ./.env
    - cp example.env ./dev.env
    - npm i
    - docker-compose -f docker-compose.test.yml up -d
    - sleep 60
    - curl http://localhost:9200
    - curl http://elasticsearch_1:9200
    - curl http://docker:9200
    - curl http://elasticsearch_1
  script:
    - npm run ci
