image: docker:19.03.0

stages:
  - test

store-test:
  stage: test
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:19.03.0-dind
  before_script:
    - apk --update add docker-compose
    - apk --update add nodejs
    - apk --update add npm
    - cd store
    - cp example.env ./.env
    - cp example.env ./dev.env
    - npm i
  script:
    - npm test
