version: "3.3"

networks:
  internal:
  external:
  elasticsearch_external:
  public:
    external:
      name: traefik_webgateway

services:
  store:
    build:
      context: .
      args:
        PORT: ${PORT}
    container_name: store
    env_file:
      - dev.env
    restart: always
    labels:
      - traefik.enable=true
      - traefik.backend=store
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:store.localhost
      - traefik.port=${PORT}
      - traefik.frontend.rateLimit.rateSet.test.period=10s
      - traefik.frontend.rateLimit.rateSet.test.burst=150
      - traefik.frontend.rateLimit.rateSet.test.average=100
      - traefik.frontend.rateLimit.extractorFunc=client.ip
    volumes:
      - ./logs:/home/dockeruser/app/logs/
    networks:
      - public # needed for traefik
      - external
      - internal
    ports:
      - "${PORT}:${PORT}"

  elasticsearch_1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0
    container_name: elasticsearch_1
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - internal
      - elasticsearch_external
    ports:
      - "9200:9200"
