version: "3.3"

services:
  store:
    build:
      context: .
      args:
        PORT: ${PORT}
    container_name: store
    env_file:
      - dev.env
    restart: always
    volumes:
      - ./logs:/home/dockeruser/app/logs/
    network_mode: host
    ports:
      - "${PORT}:${PORT}"

  elasticsearch_1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0
    container_name: elasticsearch_1
    restart: always
    network_mode: host
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch-data-test:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
