version: "3.3"

networks:
  public:
    external:
      name: traefik_webgateway

services:
  ui:
    build:
      context: .
      args:
        PORT: ${PORT}
    container_name: ui
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    labels:
      - traefik.enable=true
      - traefik.backend=ui
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:aggregationhub.${SERVER_HOST}
      - traefik.port=${PORT}
      - traefik.frontend.rateLimit.rateSet.test.period=10s
      - traefik.frontend.rateLimit.rateSet.test.burst=150
      - traefik.frontend.rateLimit.rateSet.test.average=100
    volumes:
      - ./logs/:/home/dockeruser/app/logs/
    networks:
      - public
