version: "3.3"

services:
  modules-server:
    container_name: modules-server
    build:
      context: .
      args:
        PORT: ${PORT}
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_SERVER=http://postgres:5432
      - DB_NAME=modules
      - PORT=3004
      - WAIT_HOSTS=postgres:5432
      - DATA_STORE_URL=http://store:3003
      - SERVICE_URL=http://modules-server:3004
      - DB_USERNAME=user
      - DB_PASSWORD=password
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./logs/:/home/dockeruser/app/logs/
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres-data-test/postgres:/var/lib/postgresql/data
    restart: always
