version: "3.3"

services:
  modules-server:
    container_name: modules-server
    build:
      context: .
      args:
        PORT: ${PORT}
    env_file:
      - dev.env
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./logs/:/home/dockeruser/app/logs/
  typescript-express-module-example:
    container_name: typescript-express-module-example
    build:
      context: ../modules/typescript-express-module-example
      args:
        PORT: ${MODULE_PORT}
    env_file:
      - ../modules/typescript-express-module-example/dev.env
    restart: always
    ports:
      - "${MODULE_PORT}:${MODULE_PORT}"
    volumes:
      - ./logs/:/home/dockeruser/app/logs/
      - ../modules/typescript-express-module-example/config.json:/home/dockeruser/app/config.json
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres-data-test/postgres:/var/lib/postgresql/data
    restart: always
