version: "3.3"

networks:
  internal:
  external:
  public:
    external:
      name: traefik_webgateway

services:
  modules-server:
    container_name: modules-server
    build:
      context: .
      args:
        PORT: ${PORT}
    env_file:
      - dev.env
    environment:
      - NODE_ENV=development
    restart: always
    ports:
      - "3004:3004"
    labels:
      - traefik.enable=true
      - traefik.backend=modules-server
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:modules.localhost
      - traefik.port=${PORT}
      - traefik.frontend.rateLimit.rateSet.test.period=10s
      - traefik.frontend.rateLimit.rateSet.test.burst=150
      - traefik.frontend.rateLimit.rateSet.test.average=100
      - traefik.frontend.rateLimit.extractorFunc=client.ip
    volumes:
      - ./logs/:/home/dockeruser/app/logs/
    networks:
      - public
      - external
      - internal
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - internal
