version: "3.3"

services:
  typescript-express-module-example:
    build:
      context: .
      args:
        PORT: ${PORT}
    container_name: typescript-express-module-example
    environment: :
      - PORT=3005
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./logs:/home/dockeruser/app/logs/
      - ./config.json:/home/dockeruser/app/config.json
