stages:
  - deploy

deploy:
  stage: deploy
  image: gitlab/dind:latest
  only:
    - "nonexistent" #"master"
  environment: production
  services:
    - docker:dind
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/gitlab_id_rsa
    - chmod 600 ~/.ssh/gitlab_id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/gitlab_id_rsa
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
    - ssh root@$DEPLOYMENT_SERVER_IP "mkdir -p traefik"
  script:
    - scp -r ./.env ./docker-compose.prod.yml ./traefik.prod.toml root@${DEPLOYMENT_SERVER_IP}:~/traefik/
    - ssh root@$DEPLOYMENT_SERVER_IP "cd traefik; mkdir -p logs; chmod -R 0777 logs; chmod +t logs; docker-compose -f docker-compose.prod.yml build; docker-compose -f docker-compose.prod.yml down; docker-compose -f docker-compose.prod.yml up -d"
