defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/_wildcard.localhost.pem"
      keyFile = "/certs/_wildcard.localhost-key.pem"

[api]
  dashboard = true


[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false

[traefikLog]
  filePath = "./logs/traefik.log"

[accessLog]
  filePath = "./logs/access.log"