stages:
  - deploy

deploy:
  stage: deploy
  image: gitlab/dind:latest
  only:
    - "master"
  environment: production
  services:
    - docker:dind
  before_script:
    - rm -rf node_modules/
    - rm -rf logs/
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/gitlab_id_rsa
    - chmod 600 ~/.ssh/gitlab_id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/gitlab_id_rsa
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
    - ssh root@$DEPLOYMENT_SERVER_IP "mkdir -p ui; cd ui; mkdir -p public; cd public; mkdir -p assets; mkdir -p css;"
  script:
    - scp -r ./.env ./components ./types ./pages ./utils ./docker-compose.prod.yml ./Dockerfile ./next.config.js ./next-env.d.ts ./package.json ./package-lock.json ./postcss.config.js ./server.js ./tsconfig.json ./.babelrc root@${DEPLOYMENT_SERVER_IP}:~/ui/
    - scp -r ./public/css/main.css root@${DEPLOYMENT_SERVER_IP}:~/ui/public/css/main.css
    - scp -r ./public/assets ./public/robots.txt root@${DEPLOYMENT_SERVER_IP}:~/ui/public/
    - ssh root@$DEPLOYMENT_SERVER_IP "cd ui; mkdir -p logs; chmod -R 0777 logs; chmod +t logs; docker-compose -f docker-compose.prod.yml build; docker-compose -f docker-compose.prod.yml down; docker-compose -f docker-compose.prod.yml up -d"
