name: Tests

on: [push]

jobs:
  store:
    
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js v11
        uses: actions/setup-node@v1
        with:
          node-version: 11.x
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Test Store
        working-directory: ./aggregation-hub/store
        run: |
          echo Running tests for store
          echo Building store
          npm install
          echo Running tests for store
          npm test
  modules-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Use Node.js v11
        uses: actions/setup-node@v1
        with:
          node-version: 11.x
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Test modules-server
        working-directory: aggregation-hub/modules-server
        run: |
          echo Running tests for modules-server
          echo Building modules-server
          npm install
          echo Running tests for modules-server
          npm test
  google-search-results-module:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js v11
        uses: actions/setup-node@v1
        with:
          node-version: 11.x
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Test google-search-results-module
        working-directory: modules/google-search-results-module
        run: |
          echo Running tests for google-search-results-module
          echo Building google-search-results-module
          npm install
          echo Running tests for google-search-results-module
          npm test
  typescript-express-module-example:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js v11
        uses: actions/setup-node@v1
        with:
          node-version: 11.x
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Test typescript-express-module-example
        working-directory: ./modules/typescript-express-module-example
        run: |
          echo Running tests for typescript-express-module-example
          echo Building typescript-express-module-example
          npm install
          echo Running tests for typescript-express-module-example
          npm test
